# original https://raw.githubusercontent.com/awslabs/amazon-eks-ami/0ccb71878f92f808dcc80d38e9cf8a296bb72b33/amazon-eks-nodegroup.yaml

AWSTemplateFormatVersion: "2010-09-09"

Description: Amazon EKS - Cluster Autoscaler Role

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: EKS Cluster
        Parameters:
          - ClusterName
          - ClusterOIDCProviderURL

Parameters:
  ClusterName:
    Type: String
    Description: The cluster name provided when the cluster was created. If it is incorrect, nodes will not be able to join the cluster.

  ClusterOIDCProviderURL:
    Type: String
    Description: The OIDC provider URL for the cluster.

Resources:
  ClusterAutoscalerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Fn::Sub:
          - |
            {
              "Version": "2012-10-17",
              "Statement": [{
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::${AccountId}:oidc-provider/${ClusterOIDCProvider}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${ClusterOIDCProvider}:sub": "system:serviceaccount:kube-system:cluster-autoscaler"
                  }
                }
              }]
            }
          - AccountId: !Ref AWS::AccountId
            ClusterOIDCProvider: !Select [1, !Split ["https://", !Ref ClusterOIDCProviderURL]]
      Path: /

  ClusterAutoscalerPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Roles:
        - !Ref ClusterAutoscalerRole
      PolicyDocument:
        Fn::Sub:
          - |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "autoscaling:DescribeAutoScalingGroups",
                    "autoscaling:DescribeAutoScalingInstances",
                    "autoscaling:DescribeLaunchConfigurations",
                    "autoscaling:DescribeTags",
                    "ec2:DescribeLaunchTemplateVersions"
                  ],
                  "Resource": "*"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "autoscaling:SetDesiredCapacity",
                    "autoscaling:TerminateInstanceInAutoScalingGroup"
                  ],
                  "Resource": "*",
                  "Condition": {
                    "StringEquals": {
                      "aws:ResourceTag/k8s.io/cluster-autoscaler/${ClusterName}": "owned"
                    }
                  }
                }
              ]
            }
          - ClusterName: !Ref ClusterName

Outputs:
  ClusterAutoscalerRole:
    Description: The name of the role for the cluster autoscaler
    Value: !Ref ClusterAutoscalerRole

  ClusterAutoscalerRoleArn:
    Description: The arn of the role for the cluster autoscaler
    Value: !GetAtt [ClusterAutoscalerRole, Arn]
