#!/usr/bin/env python
import os
import subprocess


cmd = "./tools/run_vulture.sh . --make-whitelist"
out = subprocess.run(cmd, shell=True, capture_output=True, text=True, check=True).stdout.rstrip()
pwd = os.getcwd()
print(out.replace(pwd + "/", ""))
