#!/usr/bin/env python
import subprocess
import os

cmd = 'vulture --exclude "build,venv" --ignore-decorators "@click.*,@sigopt_cli.*,@pytest.*" . --make-whitelist'
out = subprocess.run(cmd, shell=True, capture_output=True, text=True).stdout.rstrip()
pwd = os.getcwd()
print(out.replace(pwd + '/', ''))
