#!/usr/bin/env python
import subprocess
import os

cmd = './tools/run_vulture.sh . --make-whitelist'
out = subprocess.run(cmd, shell=True, capture_output=True, text=True).stdout.rstrip()
pwd = os.getcwd()
print(out.replace(pwd + '/', ''))
