# Copyright © 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
NODE_GROUP_TYPE_CPU = "cpu"
NODE_GROUP_TYPE_GPU = "gpu"
NODE_GROUP_TYPE_SYSTEM = "system"

ALL_NODE_GROUP_TYPES = {
  NODE_GROUP_TYPE_CPU,
  NODE_GROUP_TYPE_GPU,
  NODE_GROUP_TYPE_SYSTEM,
}
