# Copyright © 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
CLI_NAME = 'sigopt'
CONTROLLER_IMAGE_VERSION = "2021-10-11a"
CONTROLLER_REPOSITORY = "sigopt/controller"
DEFAULT_CONTROLLER_IMAGE = f"{CONTROLLER_REPOSITORY}:{CONTROLLER_IMAGE_VERSION}"
